### ISSUE TITLE
not sure where to go from .bins

### ISSUE THREAD

**Issue by tgelliott196** [GeorgePatsias/ScareCrow-CobaltStrike#6]
so every payload is a .bin for me except the dll that doesnt work for me.  
dont know what i'm doing wrong.  installed on kali, changed paths, loaded cna, dont know what else to do

[screenshots.docx](https://github.com/GeorgePatsias/ScareCrow-CobaltStrike/files/8004847/screenshots.docx)

**Comment by GeorgePatsias** [comment]
Hey, try not to change the name when saving the beacon and let me know if that works with you

**Comment by tgelliott196** [comment]
> Hey, try not to change the name when saving the beacon, and let me know if that works with you

I'm not changing the name.  I click listener, leave stageless, (pick from binary,control,dll,excel,msiexec,or wscript) output for x86exe or x64exe not an option.  Then I leave the domain of www.microsoft.com and click generate.  It asks me for a loader name.  I leave it black because not sure what to do here and I click generate. No matter the file type I pick minus .dll it makes a beacon called scbeacon.bin.  Not sure where to go from there.

**Comment by GeorgePatsias** [comment]
Did you follow the installation guide? and the extra packages needed to do that? Also the configuration?
Share me your cna script. Also are you doing the excel loader from linux?

**Comment by GeorgePatsias** [comment]
It needs Excel on your system to work.

**Comment by GeorgePatsias** [comment]
Ms Office. Read your tools

**Comment by tgelliott196** [comment]
unfortunately, work only gave me the Cobalstrike install for Linux and
Office is only compatible with win,mac,android.
