### ISSUE TITLE
Can't find compiled ScareCrow Go executable

### ISSUE THREAD

**Issue by Doublefire-Chen** [GeorgePatsias/ScareCrow-CobaltStrike#7]
**Describe the bug**
I clone and install ScareCrow followed by your introduction, but when  I finished all, I can't find compiled ScareCrow Go executable in the right path.

**To Reproduce**
1. cd CSAgent
2. git clone https://github.com/GeorgePatsias/ScareCrow-CobaltStrike.git
3. cd ScareCrow-CobaltStrike
4. chmod +x install.sh
5. .../install.sh
...installing...
6. cd ScareCrow
7. ls
8. See error

**Expected behavior**
I should find ScareCrow Go executable in my path, but it did't appear

**Screenshots**
<img width="1440" alt="Screen Shot 2022-06-05 at 19 29 52" src="https://user-images.githubusercontent.com/72138342/172048350-5c69b89a-5e2d-4e1b-ac56-fdc1b63098b4.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS in VMware operating on macOS Monterey Version12.4
 - CSAgent4.4( maybe this information is useless)

**Comment by GeorgePatsias** [comment]
Hello, thanks for the detailed analysis of the problem.

Can you please open the install.sh script and do the steps one by one and reply if there was an error and where.

```
sudo apt-get install openssl osslsigncode mingw-w64 golang -y;
git clone https://github.com/optiv/ScareCrow;
cd ScareCrow;
go get github.com/fatih/color;
go get github.com/yeka/zip;
go get github.com/josephspurrier/goversioninfo;
go build ScareCrow.go
```

**Comment by Doublefire-Chen** [comment]
![Uploading Screen Shot 2022-06-06 at 07.13.59.png…]()
error occurred. Need help.

**Comment by sec13b** [comment]
@Doublefire-Chen  try with sudo su
